### ISSUE TITLE
0 sized patched jar causes paperclip to stall

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/Paperclip#19]
If a jar file is 0 sized, the readFully method ends up stalling the startup without any form of output

```java
"main" #1 prio=5 os_prio=31 tid=0x00007fc184003800 nid=0xe03 runnable [0x000070000d8b9000]
   java.lang.Thread.State: RUNNABLE
    at io.papermc.paperclip.Paperclip.readFully(Paperclip.java:231)
    at io.papermc.paperclip.Paperclip.readBytes(Paperclip.java:242)
    at io.papermc.paperclip.Paperclip.isJarInvalid(Paperclip.java:253)
    at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:96)
    at io.papermc.paperclip.Paperclip.main(Paperclip.java:45)
```

**Comment by DemonWav** [comment]
Why would a jar be 0 sized?

**Comment by electronicboy** [comment]
I replicated this by forcefully killing paperclip while it was patching, I have no idea how this would happen in the real world unless you did similar, all I know is that it does seem to have impacted a handful of people which was a doozy to diagnose

**Comment by DemonWav** [comment]
Gotcha, thanks.
