### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by zLupa** [PaperMC/Paperclip#21]
```
[root@lupa lobby]# java -jar server.jar 
Downloading vanilla jar...
Exception in thread "main" java.lang.InternalError: java.util.zip.ZipException: error in opening zip file
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1052)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:215)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList.getService(ProviderList.java:331)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:1002)
	at java.net.URL.openStream(URL.java:1068)
	at io.papermc.paperclip.Paperclip.checkVanillaJar(Paperclip.java:181)
	at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:112)
	at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:91)
	at io.papermc.paperclip.Paperclip.main(Paperclip.java:45)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:940)
	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:801)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:886)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:879)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:878)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1050)
	... 31 more
```

### Plugin list:
- No plugins

### Actions to reproduce (if known):
Start the server and that error appear

### Paper version:
Can't run the server to do '/version,' but i'm using the build **148** from papermc 1.16.2

**Comment by DemonWav** [comment]
I think something is wrong with your JDK.

It's failing when trying to load the `SSLContextSpi` implementation for the SSL protocol (whichever protocol it is).

What's supposed to happen when an implementation can't be found is `NoSuchAlgorithmException` is thrown. This is not what's happening. Instead, the classloader is throwing an error stating the zip (jar) file is corrupt when it attempts to load that class. 

> Note: This does _not_ mean the JDK found or didn't find the implementation needed for the protocol. This exception was thrown while attempting to enumerate the implementations to find the right one in the first place. This is one of those things which should never happen.

Now what I must stress is all of this code I'm referring to is inside the JDK. All Paperclip is doing here is attempting to open a connection with the URL to download the vanilla jar. This makes me almost certain that your JDK installation is broken.
