### ISSUE TITLE
Incompatibe with GraalVM

### ISSUE THREAD

**Issue by ishland** [PaperMC/Paperclip#26]
*** Description ***
I am unable to get paperclip patch vanilla jar with GraalVM. Works fine with AdoptOpenJDK 11 HotSpot

*** Error output ***
```
$ java -jar paperclip.jar 
Patching vanilla jar...
Failed to patch vanilla jar
java.io.IOException: BZip2 CRC error
    at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.endBlock(BZip2CompressorInputStream.java:344)
    at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartA(BZip2CompressorInputStream.java:883)
    at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartB(BZip2CompressorInputStream.java:933)
    at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read0(BZip2CompressorInputStream.java:228)
    at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read(BZip2CompressorInputStream.java:179)
    at org.jbsdiff.Patch.read(Patch.java:130)
    at org.jbsdiff.Patch.patch(Patch.java:95)
    at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:151)
    at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:94)
    at io.papermc.paperclip.Paperclip.main(Paperclip.java:48
```

*** `java -version` output ***
```
java version "11.0.8.0.2" 2020-07-09 LTS
Java(TM) SE Runtime Environment GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03, mixed mode, sharing)
```

**Comment by clrxbl** [comment]
https://github.com/oracle/graal/issues/2534
First result on Google

**Comment by electronicboy** [comment]
This is a VM bug which is out of our control, apparently the CE edition does not have this bug (likely, as it's lacking the optimization which causes these issues or something)
