### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by TitasPi** [PaperMC/Paperclip#31]
**After updating java I get this exception:**
`Exception in thread "main" java.lang.IllegalArgumentException
        at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.appendToSystemClassLoaderSearch(InstrumentationImpl.java:223)
        at io.papermc.paperclip.Agent.addToClassPath(Agent.java:39)
        at io.papermc.paperclip.Paperclip.getMainMethod(Paperclip.java:225)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:51)`
**I used this command to start the server: `java -jar paper-1.16.4-340.jar`
Tried with these java versions:**
`openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)`
`openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.9.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.9.1+9, mixed mode)`

**Comment by TitasPi** [comment]
Never mind this issue. Issue was in path name having weird characters.
